NAME = pyspark-runtime
TAG  = jupyter

BUILD_EXTRA_ARGS = --build-arg DEPLOYMENT_NAME=$(DEPLOYMENT_NAME) --build-arg AWS_ACCOUNT_ID=$(AWS_ACCOUNT_ID) --build-arg AWS_REGION=$(AWS_REGION)

include ../../utils/docker.mk
