AWSTemplateFormatVersion: 2010-09-09
Description: Amazon EMR - Common cluster template

Parameters:
  DeploymentName:
    Description: Name of this EMR deployment (to isolate multiple deployments)
    Type: String

  ReleaseLabel:
    Description: EMR release to use
    Type: String
    Default: emr-6.4.0 # emr-5.33.1

Conditions:
  IsEmr6: !Equals [!Select [0, !Split ['.', !Select [1, !Split ['-', !Ref ReleaseLabel]]]], '6']

Resources:
  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Applications:
        - { Name: Spark }
        - { Name: Zeppelin }
        - { Name: Livy }
      BootstrapActions:
        - Name: SetupJupyter
          ScriptBootstrapAction:
              Path:
                Fn::Sub:
                - "s3://${Bucket}/bootstrap-jupyter.sh"
                - Bucket:
                    Fn::ImportValue: !Sub ${DeploymentName}-infra-BootstrapBucket
              Args:
                - !Sub ${DeploymentName}
      Configurations:
        - Fn::If:
            - IsEmr6
            - Classification: "container-executor"
              Configurations:
                - Classification: docker
                  ConfigurationProperties:
                    docker.trusted.registries: !Sub "local,centos,${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"
                    docker.privileged-containers.registries: !Sub "local,centos,${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com"
            - !Ref AWS::NoValue
        - Classification: "zeppelin-env"
          Configurations:
            - Classification: "export"
              ConfigurationProperties:
                ZEPPELIN_NOTEBOOK_STORAGE: org.apache.zeppelin.notebook.repo.S3NotebookRepo
                ZEPPELIN_NOTEBOOK_S3_BUCKET:
                  Fn::ImportValue: !Sub ${DeploymentName}-infra-NotebookBucket
                ZEPPELIN_NOTEBOOK_S3_USER: zeppelin
      Instances:
        CoreInstanceFleet:
          InstanceTypeConfigs:
            - { InstanceType: m5.xlarge }
            - { InstanceType: c5.xlarge }
            - { InstanceType: r5.xlarge }
          Name: Core
          TargetOnDemandCapacity: 0
          TargetSpotCapacity: 1
        Ec2SubnetId: !ImportValue infra-vpc-sn-public-a
        EmrManagedMasterSecurityGroup:
          Fn::ImportValue: !Sub ${DeploymentName}-infra-MasterSecurityGroup
        EmrManagedSlaveSecurityGroup:
          Fn::ImportValue: !Sub ${DeploymentName}-infra-WorkerSecurityGroup
        MasterInstanceFleet:
          InstanceTypeConfigs:
            - { InstanceType: m5.xlarge }
            - { InstanceType: c5.xlarge }
            - { InstanceType: r5.xlarge }
          Name: Driver
          TargetOnDemandCapacity: 0
          TargetSpotCapacity: 1
        # ServiceAccessSecurityGroup:
        #   Fn::ImportValue: !Sub ${DeploymentName}-infra-ServiceAccessSecurityGroup
      JobFlowRole:
        Fn::ImportValue: !Sub ${DeploymentName}-infra-EmrInstanceRole
      LogUri:
        Fn::Sub:
          - "s3://${Bucket}/${DeploymentName}/emr/"
          - { Bucket: !ImportValue "infra-buckets-LogBucket" }
      Name: !Sub "${AWS::StackName}"
      ReleaseLabel: !Ref ReleaseLabel
      ServiceRole:
        Fn::ImportValue: !Sub ${DeploymentName}-infra-EmrServiceRole
      Tags:
        - { Key: Name, Value: !Sub "${AWS::StackName}" }
      VisibleToAllUsers: true
